### ISSUE TITLE
Problema con Importación del horario con archivo DEL

### ISSUE THREAD

**Issue by jcapsal840** [IESMonterroso/IESMonterroso#1]
Buenas tardes.
Soy Jorge Caparrós Salmerón, profesor del IES Huelin y Coordinador TDE en dicho centro.
Tenemos un problema para configurar bien la intranet del instituto.
Desde el curso pasado vengo notando que al importar el horario desde el fichero de texto DEL correspondiente al horario de profesores creado con la herramienta Horw (nosotros lo hacemos de esto modo en vez de utilizar la otra opción mediante el archivo .xml ya que no nos funcionaba), resulta que no se actualiza la tabla Horw de la base de datos, es decir, no realiza ninguna acción sobre la base de datos. No muestra ningún mensaje de que se ha realizado correctamente o, por contra, ha habido algún problema.

Ahora mismo la tabla Horw de nuestra base de datos está vacía. Antes no lo estaba ya que contenía horarios que algunos profesores/as habían introducido manualmente, pero lo he eliminado para probar si estando vacía la tabla funcionaba el proceso de importación, pero tampoco actualiza la información.
Como he mencionado antes, algunos profesores habían introducido su horario manualmente en la intranet y cuando realizaba esta operación de importar el horario desde el fichero de texto DEL sí salía un mensaje en la parte superior diciendo "Ya existe información en la base de datos. Este proceso actualizará la información de los horarios. Realice una copia de seguridad antes de proceder a la importación de los datos.", pero realmente no realiza ninguna actualización de la tabla Horw en la base de datos, seguía conteniendo los datos que esos profesores habían introducido manualmente.
Le adjunto el fichero de los horarios que estoy intentando importar por si lo necesita para hacer alguna prueba.
No entiendo donde puede estar el problema, los demás ficheros se han importado bien y se actualizan sin problemas.

Otra cuestión, nosotros tenemos la versión Versión 4.64.2 de la Intranet y he visto que IES Monterroso utiliza la Versión 4.70.5. No sé si esto también puede ser causa de que haya fallos. Yo pulso en la Configuración en Comprobar actualizaciones y me indica que no hay actualizaciones disponibles. ¿Qué debemos hacer para conseguir una versión más actual de dicha herramienta?

Quedo a la espera de una pronta respuesta.
Saludos
[horario_Horw_IES Huelin_Málaga.txt](https://github.com/IESMonterroso/IESMonterroso/files/12777012/horario_Horw_IES.Huelin_Malaga.txt)

**Comment by mgarcia39** [comment]
Hola, Jorge.
El problema con la importación del horario en formato DEL se ha solucionado en la última versión.
Para actualizar la aplicación, debes entrar como admin o miembro del grupo Admin. Debería aparecer la opción de actualizar.
Ponte en contacto si siguen los problemas.
Un saludo.

**Comment by rubenlh91** [comment]
Buenas Jorge,
El código fuente de la Intranet, a partir de julio de 2023, no es público. Para poder actualizar a la última versión requiere que el centro tenga un contrato de servicio de mantenimiento. En el README.md de este repositorio tienes un email de contacto donde algún miembro del Equipo Directivo debe solicitar el servicio. Le pasaremos las tarifas y contrato con las condiciones.
Un saludo.

**Comment by jcapsal840** [comment]
Buenas tardes.
Muchas gracias por tu rápida respuesta.
Yo accedo siempre como administrador (admin) y al intentar actualizar me
dice que ya está actualizado. Pero la versión de  la aplicación que tenemos
es la que te he indicado en la incidencia y sigue sin actualizarse y con el
problema de los horarios.
A ver si podemos dar con la solución pronto.
Muchas gracias

**Comment by jcapsal840** [comment]
Buenas noches.
No recuerdo que se haya recibido ninguna notificación o correo en nuestro
instituto en el que se nos indicara que a partir de julio de 2023 ya no es
público el código fuente de la aplicación Intranet y que para poder seguir
utilizando una versión actualizada hay que realizar un contrato de
mantenimiento.
Mañana lo hablaré con el equipo directivo de mi centro y le enviaremos el
correo para solicitar tarifas y condiciones del contrato, dado que
necesitamos seguir utilizando dicha herramienta porque nos facilita muchas
labores en el instituto.
Le paso el correo electrónico del centro, por si puede enviar ya dicha
información.
***@***.***
Un saludo.

**Comment by mgarcia39** [comment]
Pásame tu correo personal, Jorge.
Mi dirección es ***@***.***

**Comment by jcapsal840** [comment]
Buenos días.
Mi correo personal es ***@***.***

Un saludo

**Comment by rubenlh91** [comment]
Se procede a eliminar esta issue dada la publicación de información con carácter personal de profesorado del centro educativo. Como se ha comentado en el hilo, es necesario que algún miembro del equipo directivo contacte con nosotros mediante la dirección de correo electrónico indicada en el README.md, para proceder al envío del código fuente para la instalación manual o formalización de un contrato de mantenimiento para la instalación automática de actualizaciones.
